<a href="https://colab.research.google.com/github/mszczepan/data-science-bootcamp/blob/main/02_Pandas%5C04_Laczenie_danych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [10]:
# Za≈Çadowanie danych
import pandas_datareader as web

df = web.DataReader(name='MAZN', data_source='stooq')

apple = web.DataReader(name='AAPL', data_source='stooq')
amazon = web.DataReader(name='AMZN', data_source='stooq')
google = web.DataReader(name='GOOGL', data_source='stooq')
uber = web.DataReader(name='UBER', data_source='stooq')

In [6]:
apple.info()
apple.head()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1256 entries, 2023-07-25 to 2018-07-27
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    1256 non-null   float64
 1   High    1256 non-null   float64
 2   Low     1256 non-null   float64
 3   Close   1256 non-null   float64
 4   Volume  1256 non-null   float64
dtypes: float64(5)
memory usage: 58.9 KB

              Open    High      Low   Close      Volume
Date
2023-07-25  193.33  194.44  192.915  193.62  37283201.0
2023-07-24  193.41  194.91  192.250  192.75  45505097.0
2023-07-21  194.10  194.97  191.230  191.94  71951683.0
2023-07-20  195.09  196.47  192.495  193.13  59581196.0
2023-07-19  193.10  198.23  192.650  195.10  80507323.0

In [11]:
apple.columns =  ['apple_' + col.lower() for col in apple.columns]
amazon.columns =  ['amazon_' + col.lower() for col in amazon.columns]
google.columns =  ['google_' + col.lower() for col in google.columns]
uber.columns =  ['uber_' + col.lower() for col in uber.columns]

            apple_open  apple_high  apple_low  apple_close  apple_volume
Date
2023-07-25    193.3300    194.4400   192.9150     193.6200  3.728320e+07
2023-07-24    193.4100    194.9100   192.2500     192.7500  4.550510e+07
2023-07-21    194.1000    194.9700   191.2300     191.9400  7.195168e+07
2023-07-20    195.0900    196.4700   192.4950     193.1300  5.958120e+07
2023-07-19    193.1000    198.2300   192.6500     195.1000  8.050732e+07
...                ...         ...        ...          ...           ...
2018-08-02     48.0624     49.9317    48.0096      49.6945  2.604349e+08
2018-08-01     47.7164     48.3435    47.2748      48.2857  2.835208e+08
2018-07-31     45.5980     46.0365    45.3656      45.5950  1.643182e+08
2018-07-30     45.9827     46.0485    45.3019      45.5042  8.776400e+07
2018-07-27     46.7205     46.7703    45.5510      45.7664  1.002609e+08

[1256 rows x 5 columns]

# Konkatenacja danych

In [14]:
df = pd.concat(objs = [apple, amazon, google, uber], axis = 1)

In [18]:
from re import X
pd.set_option('display.float_format', lambda x: f'{x:.2f}')
df.describe().T

,count,mean,std,min,25%,50%,75%,max
apple_open,1256.00,110.41,46.94,34.74,58.88,123.62,148.77,195.09
apple_high,1256.00,111.73,47.46,35.16,59.68,125.20,150.57,198.23
apple_low,1256.00,109.18,46.46,34.26,57.95,122.46,147.44,192.91
apple_close,1256.00,110.52,46.99,34.31,59.04,124.01,149.11,195.10
apple_volume,1256.00,111888778.93,56632034.33,31458198.00,75211867.92,97027216.30,132048320.83,434708544.96
amazon_open,1256.00,123.44,32.94,67.30,93.20,115.65,158.34,187.20
amazon_high,1256.00,124.97,33.24,69.80,94.35,117.71,159.95,188.65
amazon_low,1256.00,121.77,32.57,65.35,92.20,113.79,156.25,184.84
amazon_close,1256.00,123.38,32.86,67.20,93.23,115.52,158.10,186.57
amazon_volume,1256.00,82409031.28,38255185.46,17626740.00,56622198.75,70989000.00,97494825.00,311345660.00
google_open,1256.00,91.51,29.63,49.22,62.19,88.79,116.14,151.25
google_high,1256.00,92.57,29.93,50.61,62.67,89.87,117.88,151.55
google_low,1256.00,90.49,29.30,48.88,61.57,87.70,114.84,148.90
google_close,1256.00,91.55,29.61,49.23,62.11,88.71,116.53,149.84
google_volume,1256.00,34714140.47,15349936.01,9312760.00,25108005.00,30917050.00,39721720.00,133177100.00
uber_open,1059.00,37.21,9.42,15.96,30.37,34.91,43.75,63.25
uber_high,1059.00,37.97,9.49,17.80,30.98,35.70,44.38,64.05
uber_low,1059.00,36.41,9.27,13.71,29.66,34.06,43.01,60.80
uber_close,1059.00,37.19,9.37,14.82,30.34,34.82,43.67,63.18
uber_volume,1059.00,25341309.26,16219040.84,3380003.00,15934606.00,21626037.00,29998461.50,186322536.00

In [20]:
df

,apple_open,apple_high,apple_low,apple_close,apple_volume,amazon_open,amazon_high,amazon_low,amazon_close,amazon_volume,google_open,google_high,google_low,google_close,google_volume,uber_open,uber_high,uber_low,uber_close,uber_volume
Date,,,,,,,,,,,,,,,,,,,,
2018-07-27,46.72,46.77,45.55,45.77,100260887.19,93.80,94.00,90.33,90.86,193619180,64.46,64.57,62.23,62.64,48361800,NaN,NaN,NaN,NaN,NaN
2018-07-30,45.98,46.05,45.30,45.50,87763998.93,91.37,91.47,88.30,88.96,131246420,62.25,62.64,61.21,61.50,43896740,NaN,NaN,NaN,NaN,NaN
2018-07-31,45.60,46.04,45.37,45.59,164318201.55,89.32,90.09,86.97,88.87,114774260,61.59,62.06,60.81,61.36,39382220,NaN,NaN,NaN,NaN,NaN
2018-08-01,47.72,48.34,47.27,48.29,283520777.25,89.20,89.92,88.80,89.86,83061920,61.96,62.30,61.25,61.65,36994800,NaN,NaN,NaN,NaN,NaN
2018-08-02,48.06,49.93,48.01,49.69,260434938.64,89.44,91.83,89.30,91.72,87093620,60.92,62.22,60.90,62.06,34703600,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-19,193.10,198.23,192.65,195.10,80507323.00,133.39,135.99,132.53,135.36,54531037,124.60,125.18,121.80,122.03,37224033,47.10,47.90,46.55,47.12,21990935.00
2023-07-20,195.09,196.47,192.50,193.13,59581196.00,134.07,134.79,129.33,129.96,59820579,121.42,124.09,118.22,119.20,37906763,46.07,47.50,45.86,46.57,23085271.00
2023-07-21,194.10,194.97,191.23,191.94,71951683.00,131.34,131.37,128.41,130.00,133307294,120.62,120.99,118.73,120.02,71606474,46.55,47.34,46.28,47.23,20181244.00
2023-07-24,193.41,194.91,192.25,192.75,45505097.00,130.31,131.66,128.35,128.80,45671535,121.66,123.00,120.98,121.53,29723667,47.06,47.55,46.84,47.32,16669824.00
2023-07-25,193.33,194.44,192.91,193.62,37283201.00,129.31,129.58,128.53,129.13,39236663,121.36,123.14,121.02,122.21,52509551,47.20,47.73,46.93,47.17,14188200.00

In [23]:
closes = [col for col in df.columns if 'close' in col ]
closes
df[closes]

            apple_close  amazon_close  google_close  uber_close
Date
2018-07-27        45.77         90.86         62.64         NaN
2018-07-30        45.50         88.96         61.50         NaN
2018-07-31        45.59         88.87         61.36         NaN
2018-08-01        48.29         89.86         61.65         NaN
2018-08-02        49.69         91.72         62.06         NaN
...                 ...           ...           ...         ...
2023-07-19       195.10        135.36        122.03       47.12
2023-07-20       193.13        129.96        119.20       46.57
2023-07-21       191.94        130.00        120.02       47.23
2023-07-24       192.75        128.80        121.53       47.32
2023-07-25       193.62        129.13        122.21       47.17

[1256 rows x 4 columns]

# Metoda append()

In [24]:
uber.head()

            uber_open  uber_high  uber_low  uber_close  uber_volume
Date
2023-07-25      47.20      47.73     46.93       47.17     14188200
2023-07-24      47.06      47.55     46.84       47.32     16669824
2023-07-21      46.55      47.34     46.28       47.23     20181244
2023-07-20      46.07      47.50     45.86       46.57     23085271
2023-07-19      47.10      47.90     46.55       47.12     21990935

In [27]:
uber_6 = uber[uber.index.month == 6]
uber_7 = uber[uber.index.month == 7]

In [30]:
uber6_7 = uber_6.append(uber_7)
uber6_7

<ipython-input-30-272ad53c9249>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  uber6_7 = uber_6.append(uber_7)

            uber_open  uber_high  uber_low  uber_close  uber_volume
Date
2023-06-30      43.11      43.43     42.92       43.17     17589240
2023-06-29      44.09      44.28     42.11       42.58     28595285
2023-06-28      43.50      45.24     43.32       44.24     28187374
2023-06-27      44.69      44.83     43.75       43.83     29652066
2023-06-26      43.75      45.04     43.68       44.42     33692974
...               ...        ...       ...         ...          ...
2019-07-08      43.59      43.85     42.75       42.95      9304101
2019-07-05      44.31      44.55     43.01       43.53      8239452
2019-07-03      44.00      44.46     43.79       44.23      3380003
2019-07-02      44.55      44.68     43.75       44.00     11881274
2019-07-01      46.98      47.04     44.06       44.27     17739998

[207 rows x 5 columns]